const LoadingAnimation =  () => {
    return (
        // generated by https://loading.io/
        
        <div className="loadingio-spinner-ellipsis-63b9hxfcq3">
            <div className="ldio-wv6ewxaub0r">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    )
}

export default LoadingAnimation;